### ISSUE TITLE
Use argon2 instead of bcrypt

### ISSUE THREAD

**Issue by valkyrienyanko** [Raccoons-Rise-Up/website#1]
Someone suggested to use argon2 over bcrypt due to some sort of security issues with bcrypt.

bcrypt should eventually be replaced with argon2

https://cnpmjs.org/package/argon2

**Comment by 0HyperCube** [comment]
Argon2i also has security flaws - https://en.wikipedia.org/wiki/Argon2#Cryptanalysis (which happens to be the default in your package)

**Comment by valkyrienyanko** [comment]
I'll just stick with bcrypt for now.
