### ISSUE TITLE
Encrypt / Decrypt PBKDF2 Password Hash

### ISSUE THREAD

**Issue by valkyrienyanko** [Raccoons-Rise-Up/website#4]
## Issue
The game-server and game-client use PBKDF2 encryption however this has not been implemented for the web-server. (web-server is currently using bcrypt encryption)

Game-server / game-client implementation of PBKDF2 create a password hash with the following.
1. Salt
2. Password
3. Iteration Count

But the with the web-server implementation of PBKDF2 does not look the same, the function returns some kind of buffer object and not a string.

This needs to be decoded somehow on the web-server. (Please see the PBKDF2 implementations in the game-client and game-server below)

Game-Server-CSharp and Client-Godot-CSharp use the following implementation of PBKDF2 encryption. https://lockmedown.com/hash-right-implementing-pbkdf2-net/ Security code for game-server can be found [here](https://github.com/Kittens-Rise-Up/server/blob/main/src/Server/ENetSecurity.cs) and client [here](https://github.com/Kittens-Rise-Up/client-godot/blob/main/Scripts/Netcode/ENetSecurity.cs)

Note that game server and client don't just hash the password but the salt, the password, and the iteration count.

I found this great example of using PBKDF2 in nodejs [here](https://gist.github.com/skeggse/52672ddee97c8efec269). Problem is this does not handle a password hash which has a salt/password/interation count in it. So the solution is to figure out how to decode the data sent from the game server in the web server into more readable separate data (e.g. salt, interation count) and to use that in the example provided above.

This is how it will work. Player creates account through web-server, password hash should be encrypted same as game server and client does it. Player logs in through game client, game server verifies with web server that this is the correct password hash.

This also means the web-server will no longer be using bcrypt.

## Steps to Reproduce
Steps to reproduce problem
1. Host godot game client
2. Host game-server
3. Host web-server
4. Connect game client to game server to web server (just click on Connect in client)
5. Compare the hash in web-server (TO BE DONE)

## Solution
Code a NodeJS implementation of PBKDF2 that outputs a simiarly formatted hash as the C# implementation.

## Notice
**If it is your first time here, and you find any of this confusing, please contact me by joining [this Discord](https://discord.gg/cDNf8ja) and ping my Discord username valk#9904.**

## Code
Code pasted here for quick reference / compare. Note that this code is copy pasted from others (I did not code these functions)

NodeJS Implementation (im unsure what this exactly returns)
```js
/**
 * Hash a password using Node's asynchronous pbkdf2 (key derivation) function.
 *
 * Returns a self-contained buffer which can be arbitrarily encoded for storage
 * that contains all the data needed to verify a password.
 *
 * @param {!String} password
 * @param {!function(?Error, ?Buffer=)} callback
 */
function hashPassword(password, callback) {
  // generate a salt for pbkdf2
  crypto.randomBytes(config.saltBytes, function(err, salt) {
    if (err) {
      return callback(err);
    }

    crypto.pbkdf2(password, salt, config.iterations, config.hashBytes,
      function(err, hash) {

      if (err) {
        return callback(err);
      }

      var combined = new Buffer(hash.length + salt.length + 8);

      // include the size of the salt so that we can, during verification,
      // figure out how much of the hash is salt
      combined.writeUInt32BE(salt.length, 0, true);
      // similarly, include the iteration count
      combined.writeUInt32BE(config.iterations, 4, true);

      salt.copy(combined, 8);
      hash.copy(combined, salt.length + 8);
      callback(null, combined);
    });
  });
}
```

C# Implementation (contains salt, hash value, interation count in string)
```cs
public static string CreatePasswordHash(string password)
{
    var salt = GenerateRandomSalt();
    var iterationCount = 24000;
    var hashValue = GenerateHashValue(password, salt, iterationCount);
    var iterationCountBtyeArr = BitConverter.GetBytes(iterationCount);
    var valueToSave = new byte[SaltByteLength + DerivedKeyLength + iterationCountBtyeArr.Length];
    Buffer.BlockCopy(salt, 0, valueToSave, 0, SaltByteLength);
    Buffer.BlockCopy(hashValue, 0, valueToSave, SaltByteLength, DerivedKeyLength);
    Buffer.BlockCopy(iterationCountBtyeArr, 0, valueToSave, salt.Length + hashValue.Length, iterationCountBtyeArr.Length);
    return Convert.ToBase64String(valueToSave);
}
```

**Comment by 0HyperCube** [comment]
@valkyrienyanko In node, a buffer object is a byte array and can be converted to a string with the following method: https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end

To make the node implementation produce the same result as the c# (assuming salt length is the same) put the following at the end of the implementation
```ts
     const iterationCountBtyeArr = Buffer.from(config.iterations);
      var combined = new Buffer(hash.length + salt.length + 4);
      salt.copy(combined, 0);
      hash.copy(combined, salt.length);
      combined.writeInt32BE(config.iterations, salt.length + hash.length, true);
      callback(null, combined);
```

**Comment by 0HyperCube** [comment]
@valkyrienyanko For verifying, you need to know how long the salt is. You could do this by first encoding an i32 for the length of the salt.

**Comment by valkyrienyanko** [comment]
The length of the salt is known in the C# implementation. (even the password key length is known)

https://github.com/Kittens-Rise-Up/server/blob/04fa4d520072be62051d4970784b849c10bc7507/src/Server/ENetSecurity.cs#L8

**Comment by 0HyperCube** [comment]
@valkyrienyanko If those are both 24 bytes then it is very easy to decrypt:
```ts
function verifyPassword(password, combined, callback) {
  // extract the salt and hash from the combined buffer
  var salt = combined.slice(0, 24);
  var hash = combined.toString('binary', 24, 48);
  var iterations = combined.readInt32BE(48);

  // verify the salt and hash against the password
  crypto.pbkdf2(password, salt, iterations, 24, function(err, verify) {
    if (err) {
      return callback(err, false);
    }

    callback(null, verify.toString('binary') === hash);
  });
}
```

**Comment by valkyrienyanko** [comment]
Could you create a pull request for game-server / web-server and get this working please?

**Comment by valkyrienyanko** [comment]
The above design is bad and will be rethought with JWTs. Closing this issue and will open up a new one if I have troubles with new JWT design.
